#!/bin/bash
# Prio: 2

. /usr/lib/openapp-backup/includes/index

###
# This script will set the siteurl to the primary ip of this box

BACKUPDIR=$1
ACTION=$2

run_backup() {
	[ -r /etc/openapp-mysql/lighttpd.passwd ] && cp /etc/openapp-mysql/lighttpd.passwd ${BACKUPDIR}
}

run_restore() {
	if [ -r ${BACKUPDIR}/lighttpd.passwd ]; then
		PASSWORD=$(cat ${BACKUPDIR}/lighttpd.passwd | cut -f2 -d:)
		echo ${PASSWORD} | openapp-mysql-passwd stdin > /dev/null
	fi
}

case ${ACTION} in
    backup)
		run_backup
    ;;
    restore)
		run_restore
    ;;
esac
